#!/usr/bin/env bash

set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

dotfiles::apply_templating() {
  if platform::is_macos; then
    sed -i '' -e "s|XXX_DOTFILES_PATH_XXX|$DOTFILES_PATH|g" "$DOTFILES_PATH/shell/zsh/.zshenv"
  else
    sed -i -e "s|XXX_DOTFILES_PATH_XXX|$DOTFILES_PATH|g" "$DOTFILES_PATH/shell/zsh/.zshenv"
  fi
}

##? Create the dotfiles structure
##?
##? Usage:
##?    create [dotfiles_path]
##?

if  [[ ! -d "$DOTFILES_PATH/symlinks" ]]; then
  cp -r "$DOTLY_PATH/dotfiles_template/"* "$DOTFILES_PATH/"

  dotfiles::apply_templating

  log::success "Done!"
else
  output::answer "Dotfiles already exists, skipping to next step"
fi
